# Generated by Django 5.1.5 on 2025-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
